---
title: "INFSCI 2595 Final Project"
subtitle: "Part 2D4, Regression - Best Model"
author: "Zhenyu Li"
date: '2022-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_linedraw())
library(tidymodels)
tidymodels_prefer()
source("./scripts/utils.R")
```

----

## Regression: Best Model

Compare and choose the best model for the regression task from:  

- Best baseline linear model
- Best regularized Elastic Net model
- Best advanced model

**Read in the 3 best models from part 2D1 - 2D3.**  

```{r message=FALSE, warning=FALSE}
mod_2D_lm_best_resample <- readr::read_rds("./models/mod_2D_lm_best_resample")
mod_2D_enet_best_resample <- readr::read_rds("./models/mod_2D_enet_best_resample")
mod_2D_adv_best_resample <- readr::read_rds("./models/mod_2D_adv_best_resample")
my_models <- mget(ls(pattern = "^mod_2D.+_resample"))
```

**Compare model parameters.**  

```{r metrics, out.width=600, fig.width=8, fig.asp=0.4, message=FALSE, warning=FALSE}
my_models %>%
  map_dfr(collect_metrics, .id="model") %>%
  ggplot(aes(x=model, color=model)) +
  geom_pointrange(
    aes(y = mean, ymin = mean - std_err, ymax = mean + std_err, group = model)) +
  facet_wrap(~ .metric, scales = "free_y") +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
```

- For all three metrics, the best model from the Elastic Net (green) has the best performance. 
- The worst performance is from the best linear model fit from manually crafted features (blue).  
- The best model from the advanced models (XGBoost, red) has intermediate performances.  
- Thus the best model for regression task is determined to be the Elastic Net model. 

**Visualize predicted vs observed.**  

```{r predicted vs observed, out.width=900, fig.width=9, fig.asp=0.5, message=FALSE, warning=FALSE}
my_models %>%
  map_dfr(collect_predictions, .id="model") %>%
  ggplot(aes(x=response, y=.pred)) +
  geom_abline(color = "grey50", lty = 2) +
  geom_point(alpha = 0.2, size = 0.25) +
  facet_wrap(~ model) +
  coord_obs_pred() +
  labs(x = "observed", y = "predicted")
```

- From left to right are the XGBoost, the Elastic Net, and the baseline linear model.  
- We see the middle one (Elastic Net) the predicted and observed are more closely correlated.    

----



