---
title: "INFSCI 2595 Final Project"
subtitle: "Part 3D1, Classification - Resampling - GLM"
author: "Zhenyu Li"
date: '2022-04-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_linedraw())
library(tidymodels)
tidymodels_prefer()
source("./scripts/utils.R")
```

```{r message=FALSE, warning=FALSE}
df <- readr::read_csv("./data/final_project_train.csv", col_names = TRUE)
df_clas <- df %>% select(-c(rowid,response)) # remove unused columns
```

----

## Generalized Linear Models

Train the 2 predefined general linear models and 3 custom basis general linear models selected from section 2A using resampling.  

**Create the blueprints for data preprocessing & feature engineering.**  

```{r preprocess}
bp_prep_cl <- recipe(outcome ~ ., data=df_clas) %>%
  step_normalize(all_numeric_predictors())
  #prep(training=df_clas, retain=T) %>% bake(new_data=NULL)
```

### Predefined models

- `3D1`: All categorical and continuous inputs - linear additive features.

```{r mod_3D1}
bp_3D1 <- bp_prep_cl %>%
  step_dummy(all_nominal_predictors())
```

- `3D2`: All pairwise interactions of continuous inputs, include additive categorical features.
  
```{r mod_3D2}
bp_3D2 <- bp_prep_cl %>%
  step_interact(~ all_numeric_predictors():all_numeric_predictors(), sep = ":") %>%
  step_dummy(all_nominal_predictors())
```

### Custom models

- Import previous models that are referenced here.

```{r}
mod_3A2 <- readr::read_rds("./models/mod_3A2")
mod_3Ac2 <- readr::read_rds("./models/mod_3Ac2")
mod_3Ac3 <- readr::read_rds("./models/mod_3Ac3")

# xw_01 + xw_02 + xw_03
# xs_03 + xs_04 + xs_05 + xs_06
```

- `3D3_3A2`: linear additive of continuous inputs only.  

```{r mod_3D3_3A2}
bp_3D3_3A2 <- bp_prep_cl %>%
  step_rm(c(region,customer))

# check # of features with corresponding model (+outcome -intercept)
bp_3D3_3A2 %>% prep(training=df_clas, retain=T) %>% bake(new_data=NULL) %>% ncol()
coef(mod_3A2) %>% length()
```

- `3D4_3Ac2`: interaction of selected continuous terms.  

mod_3Ac2 <- glm(
  outcome ~ . +
   ( xs_03 + xs_04 + xs_05 + xs_06 ) :
   ( xw_01 + xw_02 + xw_03 ),
  binomial, data=df_prep_cl)

```{r mod_3D4_3Ac2}
bp_3D4_3Ac2 <- bp_prep_cl %>%
  step_interact(~ matches("^xs_0[3,4,5,6]{1}") : starts_with("xw"), sep = ":") %>%
  step_dummy(all_nominal_predictors())

# check # of features with corresponding model (+outcome -intercept)
bp_3D4_3Ac2 %>% prep(training=df_clas, retain=T) %>% bake(new_data=NULL) %>% ncol()
coef(mod_3Ac2) %>% length()
```

- `3D5_3Ac3`: interaction from `customer` to the selected continuous inputs.  

```{r mod_3D5_3A3}
bp_3D5_3Ac3 <- bp_prep_cl %>%
  step_dummy(customer, one_hot = T) %>%
  step_interact(~ starts_with("customer_") : matches("^xs_0[3,4,5,6]{1}|^xw+"), sep = ":") %>%
  step_rm(matches("^customer_[A-Z]{1}$")) %>%
  step_dummy(region)

bp_3D5_3Ac3 %>% prep(training=df_clas, retain=T) %>% bake(new_data=NULL) %>% ncol()
coef(mod_3Ac3) %>% length()
```

----

## Resampling

### Setup

**Define the resampling scheme.**  

- Use 5 fold cross-validation with 5 repeats for resampling.
- Will compare Accuracy, ROC area under curve metrics.  

```{r resample setup}
set.seed(1324)
cv_folds <- vfold_cv(df_clas, v = 5, repeats = 5)
my_metrics_cl <- metric_set(accuracy, roc_auc, mn_log_loss)
glm_spec <- logistic_reg() %>% set_engine("glm")
```

**Create workflow set to fit.**  

```{r workflow set}
glm_wset <- workflow_set(
  preproc = list(
    all_additive = bp_3D1,
    all_cont_pairwise = bp_3D2,
    cont_add_only = bp_3D3_3A2,
    inter_selected = bp_3D4_3Ac2,
    inter_customer = bp_3D5_3Ac3
    ),
  models = list(glm = glm_spec)
  )
```


### Execute

Note: to speed up knit, these two code blocks are set `eval=FALSE`. They can be manually executed in the rmarkdown file.  

```{r execute, eval=FALSE}
tune_3D_glm <- glm_wset %>%
  workflow_map(
    fn = "fit_resamples",
    resamples = cv_folds,
    metrics = my_metrics_cl,
    control = control_resamples(save_pred = F),
    verbose = T
  )
```

```{r save_result, eval=FALSE}
readr::write_rds(tune_3D_glm,"./models/tune_3D_glm")
```

----

## Conclusions

```{r}
tune_3D_glm <- readr::read_rds("./models/tune_3D_glm")
```

### Performance

**Visualize and compare performances across 5 linear models.**  

```{r overview, out.width=800, fig.width=8, fig.asp=0.4,warning=FALSE}
tune_3D_glm %>% collect_metrics() %>%
  ggplot(aes(x=wflow_id, color=wflow_id)) +
  geom_linerange(aes(ymin=mean-std_err, ymax=mean+std_err))+
  geom_point(aes(y=mean), position = position_dodge(0.8)) +
  facet_wrap(~ .metric, scales = "free_y") +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  labs(color="model")
```

- Remove the all pairwise model and the interaction with customer model to zoom in those with better performances.  

```{r zoom in, out.width=800, fig.width=8, fig.asp=0.4,warning=FALSE}
tune_3D_glm %>% collect_metrics() %>%
  filter(!grepl("all_cont_pairwise|inter_customer", wflow_id)) %>%
  ggplot(aes(x=wflow_id, color=wflow_id)) +
  geom_linerange(aes(ymin=mean-std_err,ymax=mean+std_err)) +
  geom_point(aes(y=mean), position = position_dodge(0.8)) +
  facet_wrap(~ .metric, scales = "free_y") +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
  labs(color="model")
```

- For the all input additive model (red, `mod_3D1`) and continuous input additive model (green, `mod_3D3_3A2`), accuracy and ROC AUC performances are similar.  
- Since from EDA we know the class distribution is skewed (low event probability). Both accuracy and ROC AUC may not properly reflect model performance. Thus I opt to use them as reference, and rely mainly on mean log loss as the metric to select best model.  
- Thus the best model is `mod_3D3_3A2` (green) with continuous variables additive only.  

### Best Model

**Finalize the workflow for the best model and retrain with resampling to save predictions.** 

```{r}
glm_best_wflow_roc <- "cont_add_only_glm"

mod_3D_glm_best_wflow <- glm_wset %>%
  extract_workflow(glm_best_wflow_roc)

mod_3D_glm_best_resample <-
  mod_3D_glm_best_wflow %>%
  fit_resamples(
    cv_folds,
    metrics = my_metrics_cl,
    control = control_resamples(save_pred = T)
  )

mod_3D_glm_best_resample %>% collect_metrics() %>% select(-.config, -.estimator)
```

```{r}
save_models(mget(ls(pattern = "^mod_3D_glm")))
```

----